stages:
  - build
  - test
  #  - docker-build
  - deploy

test:
  stage: test
  image: node
  tags:
    - happy
  script:
    - echo "Testing App!"
    - CI=true npm test
    - echo "Test successfully!"

build:
  stage: build
  image: node
  tags:
    - happy
  script:
    - echo "Start building App!"
    - npm install
    - npm run build
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
      - build/
      - node_modules/

#docker-build:
#  stage: docker-build
#  image: docker:latest
#  tags:
#    - happy
#  services:
#    - name: docker:20.10.11
#  before_script:
#    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#  script:
#    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
#    - docker push "$CI_REGISTRY_IMAGE"
#    - echo "Registry image:" $CI_REGISTRY_IMAGE
# LISA SUDO ÕIGUSE KÕIGILE?!

deploy:
  stage: deploy
  tags:
    - happy
  script:
    - mkdir -p ~/front-deployment
    - rm -rf ~/front-deployment/*
    - cp -r build/. ~/front-deployment
