export let OwnersData = [
    {
        "id": 0,
        "firstName": "Farley",
        "lastName": "Mcmillan",
        "email": "farleymcmillan@zuvy.com",
        "phone": "+372 (917) 575-3674",
        "street": "Neptune Avenue",
        "house": 137,
        "apartment": 33,
        "city": "Cazadero",
        "postalIndex": 39726,
        "county": "Palau",
        "country": "USA"
    },
    {
        "id": 1,
        "firstName": "Robles",
        "lastName": "Fields",
        "email": "roblesfields@zuvy.com",
        "phone": "+372 (847) 459-3388",
        "street": "Dikeman Street",
        "house": 186,
        "apartment": 74,
        "city": "Gambrills",
        "postalIndex": 32515,
        "county": "American Samoa",
        "country": "USA"
    },
    {
        "id": 2,
        "firstName": "Morton",
        "lastName": "Coleman",
        "email": "mortoncoleman@zuvy.com",
        "phone": "+372 (807) 474-3697",
        "street": "Georgia Avenue",
        "house": 200,
        "apartment": 15,
        "city": "Vandiver",
        "postalIndex": 75311,
        "county": "Puerto Rico",
        "country": "USA"
    },
    {
        "id": 3,
        "firstName": "Antoinette",
        "lastName": "Carrillo",
        "email": "antoinettecarrillo@zuvy.com",
        "phone": "+372 (861) 481-3361",
        "street": "Woodpoint Road",
        "house": 168,
        "apartment": 174,
        "city": "Laurelton",
        "postalIndex": 29164,
        "county": "Nevada",
        "country": "USA"
    },
    {
        "id": 4,
        "firstName": "Salazar",
        "lastName": "Kelley",
        "email": "salazarkelley@zuvy.com",
        "phone": "+372 (873) 535-2551",
        "street": "Stratford Road",
        "house": 199,
        "apartment": 137,
        "city": "Celeryville",
        "postalIndex": 65508,
        "county": "Wisconsin",
        "country": "USA"
    },
    {
        "id": 5,
        "firstName": "Johnnie",
        "lastName": "Greene",
        "email": "johnniegreene@zuvy.com",
        "phone": "+372 (947) 465-2955",
        "street": "Reeve Place",
        "house": 100,
        "apartment": 52,
        "city": "Worton",
        "postalIndex": 14799,
        "county": "Missouri",
        "country": "USA"
    },
    {
        "id": 6,
        "firstName": "Craft",
        "lastName": "Glass",
        "email": "craftglass@zuvy.com",
        "phone": "+372 (909) 516-3031",
        "street": "Perry Place",
        "house": 72,
        "apartment": 199,
        "city": "Sunwest",
        "postalIndex": 48403,
        "county": "Utah",
        "country": "USA"
    }
]